// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6vuD1ocalrYKMWIdfoVNzTjwrxD_iezY',
    appId: '1:679671513577:web:dae9e21840e8ae69814b78',
    messagingSenderId: '679671513577',
    projectId: 'chatify-f7440',
    authDomain: 'chatify-f7440.firebaseapp.com',
    storageBucket: 'chatify-f7440.appspot.com',
    measurementId: 'G-TDRKMCBFG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnpQZyw7_A3wT8dyWMlNcN3Y-tBB4-Fuw',
    appId: '1:679671513577:android:c1c7d8320bf9052f814b78',
    messagingSenderId: '679671513577',
    projectId: 'chatify-f7440',
    storageBucket: 'chatify-f7440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5VU0n_yaTq3QYIsBJd5RhQHRp0IvzgwQ',
    appId: '1:679671513577:ios:988baf6510d70845814b78',
    messagingSenderId: '679671513577',
    projectId: 'chatify-f7440',
    storageBucket: 'chatify-f7440.appspot.com',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5VU0n_yaTq3QYIsBJd5RhQHRp0IvzgwQ',
    appId: '1:679671513577:ios:1d91c7944d366196814b78',
    messagingSenderId: '679671513577',
    projectId: 'chatify-f7440',
    storageBucket: 'chatify-f7440.appspot.com',
    iosBundleId: 'com.example.chatify.RunnerTests',
  );
}
